services:
  - type: web
    name: aim-health-static
    env: static
    buildCommand: "echo 'No build command needed, static HTML'"
    staticPublishPath: ./
    customDomains:
      - americaninstituteofmentalhealth.com
      - aimtomentalhealth.com
